spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeworkspring
    username: postgres
    password: 3653
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true



